################################################################################
##                             Network interface                              ##
################################################################################
server:
  # Address to which we bind (default: 127.0.0.1)
  address: "0.0.0.0"
  # Port on which we bind (default: 3000)
  port: 3001

################################################################################
##                               Logging options                              ##
################################################################################
logging:
  # The name of the folder where the logs are stored.
  folder: logs
  # Values: error, warn, info, http, verbose, debug, silly
  level: http
  # Default to false
  console: true

relay:
  managerKeys:
    - ${MANAGER_KEY1}
    - ${MANAGER_KEY2}
    - ${MANAGER_KEY3}
    - ${MANAGER_KEY4}
    - ${MANAGER_KEY5}
  accessKey: ${ACCESS_KEY}
  certifier: ${CERTIFIER_KEY}

contracts:
  tokenAddress : ${TOKEN_CONTRACT_ADDRESS}
  ledgerAddress : ${LEDGER_CONTRACT_ADDRESS}
  phoneLinkerAddress : ${PHONE_LINKER_CONTRACT_ADDRESS}

