################################################################################
##                             Network interface                              ##
################################################################################
server:
    # Address to which we bind (default: 127.0.0.1)
    address: "${HOST_IP}"
    # Port on which we bind (default: 7070)
    port: 7501

################################################################################
##                               Database options                             ##
################################################################################
database:
    host: "${DATABASE_HOST}"
    user: "${DATABASE_USER}"
    password: "${DATABASE_PASSWORD}"
    database: "${DATABASE_NAME}"
    scheme: "${DATABASE_SCHEME}"
    port: "${DATABASE_PORT}"
    connectionTimeoutMillis: 5000
    max: 100

################################################################################
##                               Logging options                              ##
################################################################################
logging:
    # Values: error, warn, info, http, verbose, debug, silly
    level: verbose

################################################################################
##                             Scheduler options                              ##
################################################################################
scheduler:
    enable: true
    items:
        - name: collectPurchase
          enable: true
          expression: "*/10 * * * * *"
        - name: collectExchangeRate
          enable: true
          expression: "*/10 * * * * *"

contracts:
    tokenAddress: "${TOKEN_CONTRACT_ADDRESS}"
    ledgerAddress: "${LEDGER_CONTRACT_ADDRESS}"
    phoneLinkerAddress: "${PHONE_LINKER_CONTRACT_ADDRESS}"
    shopAddress: "${SHOP_CONTRACT_ADDRESS}"
    currencyRateAddress: "${CURRENCY_RATE_CONTRACT_ADDRESS}"
    providerAddress: "${LOYALTY_PROVIDER_CONTRACT_ADDRESS}"
    consumerAddress: "${LOYALTY_CONSUMER_CONTRACT_ADDRESS}"
    exchangerAddress: "${LOYALTY_EXCHANGER_CONTRACT_ADDRESS}"
    purchaseAddress: "${STORE_PURCHASE_CONTRACT_ADDRESS}"

setting:
    ipfs_gateway_url: "${NODE_IPFS_GATEWAY_URL}"
    nptServer: "kr.pool.ntp.org"
    nptInterval: 10
    SECONDS_PER_SLOT: ${SECONDS_PER_SLOT}
    SLOTS_PER_EPOCH: ${SLOTS_PER_EPOCH}
    GENESIS_TIME: ${GENESIS_TIME}

validator:
    keys:
        - "${VALIDATOR01}"
        - "${VALIDATOR02}"
        - "${VALIDATOR03}"
        - "${VALIDATOR04}"
        - "${VALIDATOR05}"
        - "${VALIDATOR06}"
        - "${VALIDATOR07}"
        - "${VALIDATOR08}"
        - "${VALIDATOR09}"
        - "${VALIDATOR10}"
        - "${VALIDATOR11}"
        - "${VALIDATOR12}"
        - "${VALIDATOR13}"
        - "${VALIDATOR14}"
        - "${VALIDATOR15}"
        - "${VALIDATOR16}"
