version: "3.3"
services:
    dms-osx-faker:
        image: bosagora/dms-osx-faker:latest
        container_name: dms-osx-faker
        restart: always
        extra_hosts:
            - host.docker.internal:host-gateway
        environment:
            PRODUCTION_NET_URL: http://host.docker.internal:8545
            PRODUCTION_CHAIN_ID: 24680
