version: '3.3'

services:
  mysql:
    image: "mysql:8.0"
    cap_add:
      - SYS_NICE
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "12345678"

volumes:
  mysql_db:
