version: '3.3'
services:
  postgres:
    image: postgres:12.0
    container_name: postgres
    ports:
      - '5432:5432'
    restart: always
    command:
      [
        "postgres",
        "-c", "shared_preload_libraries=pg_stat_statements",
        "-c", "max_connections=1000"
      ]
    environment:
      POSTGRES_PASSWORD: 12345678
      POSTGRES_USER: agora
      POSTGRES_DB: postgres
      PGDATA: /postgresql/data
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - postgres_db:/postgresql/data

volumes:
  postgres_db:
