version: '3.3'
services:
  dms-osx-relay:
    image: bosagora/dms-osx-relay:latest
    container_name: dms-osx-relay
    ports:
      - '3000:3000'
    restart: always
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      HOST_IP: 0.0.0.0
      HOST_PORT: 3000
    networks:
      - default_network

networks:
  default_network:
    driver: bridge
